### ISSUE TITLE
Sparkline y-scaling can't handle outliers

### ISSUE THREAD

**Issue by davidheyman** [axismaps/ridership#11]
A lot of these MSAs contain one dominant TA with high values and then a bunch of others that are much lower. This leads to not useful sparklines that have one line on top with some variation and a bunch of flat lines on the bottom.

To examine how to fix the y-scaling, we should:

- [x] Test if square / cube root scaling will work in all cases
- [x] Develop a method to set scaling method based on factors in the data like maximum value or standard deviations from mean

We can determine which scaling method to use for an MSA based on the variance of UPT. That's a very good indicator of the size of the TA.

**Comment by awoodruff** [comment]
This seems to be improved by a tiny power function, like the 1000th(!) root, at the expense of flattening out the big outlier line and suppressing its trend. Examples from NYC are below, including a before/after of the expanded chart. I'm using a rule where if the max value is more than twice as big as the max value of the next highest line, it uses this scale, and otherwise sticks with linear.

![screen shot 2019-01-03 at 10 42 28 am](https://user-images.githubusercontent.com/3533462/50646930-5b463a80-0f45-11e9-8560-7356172a83a1.png)
![screen shot 2019-01-03 at 10 41 36 am](https://user-images.githubusercontent.com/3533462/50646945-600aee80-0f45-11e9-9b35-bd4717a3a455.png)

Below, expanded ridership with a linear scale (i.e. "before"). Clearer trend for NYCT, but everything else is jammed at the bottom.
![screen shot 2019-01-03 at 10 43 11 am](https://user-images.githubusercontent.com/3533462/50646987-7b75f980-0f45-11e9-92d3-18e9f1008877.png)

**Comment by davidheyman** [comment]
Looks good to me. We’ll have to confirm this with the client when they review it and see which one they prefer.

**Comment by davidheyman** [comment]
If this does come back, an alternative method would be standardizing by a mean of zero and scaling by standard deviation.

**Comment by davidheyman** [comment]
@awoodruff We should try the new method of scaling. In `y = mx + b` terms:

`b` = The negative mean of all years for a given indicator and a given TA
`m` = 1 / standard deviation of all years for a given indicator and given TA

I think I've done that correctly but message me if I haven't. Also, can you do this on a separate branch since it might not make it in the final version?
