### ISSUE TITLE
Mobile MSA map performance

### ISSUE THREAD

**Issue by davidheyman** [axismaps/ridership#36]
There are a few issues related to this as well. Hopefully adding the probe will resolve them.

https://www.notion.so/axismaps/Mobile-iPhone-in-the-regional-view-clicking-on-a-Census-tract-does-not-bring-up-a-pop-out-box-a-a9762bddc8c0472aa2b59d5c6e9ccece

**Comment by awoodruff** [comment]
The probe's working here, but as reported in that issue the map does tend to crash a lot in MSA view. It's generally happening to me for bigger cities where there are lots of tracts. I thought displaying tons of stuff is supposed to be one of the cool things about GL, so I'm not sure what the deal is. It performs poorly whether or not the probe interaction events are enabled.

Can tracts geodata be simplified further? Couldn't hurt, if so.

**Comment by davidheyman** [comment]
It's still crashing for me too after the simplification.

@awoodruff Can you review the code to make sure there aren't any glaring inefficiencies? Two other things to look into:

https://docs.mapbox.com/help/troubleshooting/working-with-large-geojson-data/
https://gist.github.com/ryanbaumann/04c442906638e27db9da243f29195592

I'll make a `geojson` branch to store geojson versions of these files instead of topojson and we can see if that helps.

**Comment by davidheyman** [comment]
That branch is up now. The biggest file in there is 1.2MB which is small enough that it shouldn't be causing problems.

**Comment by davidheyman** [comment]
Also, I think you have to run `npm build` to copy the files into the list directory where they are served from by the dev script.

**Comment by awoodruff** [comment]
Thanks for doing that and finding those links. I'm not sure the effect of geojson vs topojson, but after poking around some more I've found that a handful of things do (or probably do) affect the likelihood of crashing:
- Polygon simplification (probably)
- `buffer` property
- basemap complexity
- tract outline on probing
- having probe/interaction events at all

The only way so far that I haven't had _any_ crash is with a blank basemap and no interactions, which of course isn't a real solution. But a few things I'd want to try that may help:

1. set `buffer` to 0 (I'm not spotting any problems with that, so may as well)
2. a somehow simpler basemap for mobile if possible
3. use `line-width` instead of `line-opacity` as the variable on the stroke layer — no idea really if GL works at all the same way, but if it were SVG or something, a bunch of tracts with 0 width and just one with 3px would be better than all of them with 3px but 0 opacity
4. OR, work with the fill layer instead on mobile, to avoid having to add the extra stroke layer

Based on what I've seen so far, it would still probably crash on, say, NYC even if all of that were in place, but maybe it would be better than now, at least?

**Comment by davidheyman** [comment]
I'd like to see if working with GeoJSON helps at all. I guess it's only tries to convert the topology once, but it's still worth a try. You can also remove polygon simplification since it's pre-simplified in Mapshaper. After that, let's try working with the fill instead of stroke. That's my best guess for where things are falling apart.

**Comment by awoodruff** [comment]
Sorry, forgot to commit the thing that lets the geojson actually work in the map. That's up on that branch now. I couldn't discern any difference, but if it keeps things simpler then it seems like no problem to use.

**Comment by awoodruff** [comment]
A little more anecdotal info from messing around on my phone (iPhone 6) with the tracts layers as vector tiles:
- With transit lines as the only visible layers, it generally worked but I did get one crash
- With transit lines and tracts, also mostly good but an occasional crash
- With everything _except_ transit lines, no crashes so far!

This is always in NYC (presumably the most taxing metro), and just kind of quickly panning and zooming around a lot. 

Raster basemap tiles might help but I guess wouldn't 100% solve problems. Perhaps the transit line styles can be simplified somehow for mobile? Not sure what that could be besides removing line casing layers, though, which would hurt legibility. Otherwise, maybe more data processing on the transit lines—like merging/removing lines where they more or less overlap—could help but I don't know how feasible that is.

**Comment by davidheyman** [comment]
I've gone nuts with the simplification and I've gotten it stop _mostly_. The only time I've gotten it to crash is by zooming all the way, rotating, and hitting reset. 

I think we'll be there if we:

1. Disable rotation
2. Disable the animated zoom when clicking reset

**Comment by davidheyman** [comment]
I found another consistent crash that occurs when highlighting a tract polygon and moving the map. Can you remove highlights on map move?
