### ISSUE TITLE
Represent nominal yearly values in addition to change

### ISSUE THREAD

**Issue by davidheyman** [axismaps/ridership#59]
Add yearly nominal values for all years to data probes

**Comment by awoodruff** [comment]
This and #70 are for the MSA choropleth view I believe. There was a suggestion of adding nominal values as an option for display in the choropleth map itself; is putting these values in the probe an alternative to that?

Otherwise some kind of toggle for "change" vs "value" (or whatever) could be added to this control bar.
![Screen Shot 2020-01-29 at 12 27 45 PM](https://user-images.githubusercontent.com/3533462/73380929-de45db80-4292-11ea-8443-65e52dd06786.png)

**Comment by davidheyman** [comment]
This is for the MSA choropleth view. The only requested change was to add a year-by-year list to the data probe with all the yearly values included. Hopefully there’s a way to do that without overwhelming anyone with massive probes with loads of numbers in them. I’m hoping using no more than 3 significant digits will help.
