### ISSUE TITLE
Improvements to no data values

### ISSUE THREAD

**Issue by davidheyman** [axismaps/ridership#60]
- When calculating change data, use closest year of data if values are no data
- Do full design review of no data across all maps / charts / UI components and change any confusing representations

**Comment by awoodruff** [comment]
To summarize the state of no-data, including the unmerged changes:

- National map uses closest available years of data when representing % change. If there's no data  for any year (or only one year), the symbols are gray.
- MSA level choropleth map does the same, except no-data tracts are filtered out entirely. This is their original treatment but maybe they should be visible and gray instead?
- PCP also uses closest available years
- Probes for all of the above show start and end values and their actual years
- If there's no data at all to show on the map (rare), the histogram area shows a message about it.
- Data updates will clarify some issues of 0 vs null, like the Job Density example they mentioned 
- Missing data years in sparklines are simply gaps in the line, which seems fine
- Missing indicator data in the PCP also results in gaps. This is not entirely ideal because a value can't be seen if neither of its neighbors have values (takes at least two points to make a line). Maybe we can add a dot or something in those cases.

Something that has NOT been done (but was suggested in the document) is any restriction on choosing years or indicators with missing data. That would require some pretty involved changes, I think.

**Comment by davidheyman** [comment]
@awoodruff Do you want to send this for review? Let me know when you're ready for feedback. We can ask for feedback as often as we want, especially if it helps prevent merge-hell in the future.

**Comment by awoodruff** [comment]
@davidheyman Yeah, may as well. There's another branch or two coming off this one, so it would be good to sort out any big changes.

**Comment by davidheyman** [comment]
I was wrong about building the closest year feature in. Instead, just display no data values on everything and display a message that says "No data available for 20XX. Try selecting a different year or indicator"

**Comment by davidheyman** [comment]
This was approved so merge away
