### ISSUE TITLE
Clean transit line data for basemap

### ISSUE THREAD

**Issue by davidheyman** [axismaps/ridership#63]
- [ ] Verify that shapefiles for transit coded as “tram” in TL and as “streetcar” in NTD appear in application (Austin, Atlanta, perhaps others missing data).
- [ ] Update LA shapefiles to categorize FlyAway as bus

**Comment by davidheyman** [comment]
@awoodruff The first issue appears to be on the client side. Is it because the tram line doesn't have a TA?

Mapbox Studio:
![2020-04-17_09-09-10](https://user-images.githubusercontent.com/791434/79547042-45ea1680-808b-11ea-8050-2e9ad3e94cbe.png)

In the app:
![2020-04-17_09-09-37](https://user-images.githubusercontent.com/791434/79547074-51d5d880-808b-11ea-9fe2-18bea8877939.png)

**Comment by awoodruff** [comment]
Yes, it looks like a lack of `taid` is why; there's a filter based on TA ids for the MSA, I guess mainly so that lines in neighboring cities don't show up. (The NYC map extent, for example, would include several other nearby MSAs.)

If it would be a sufficient solution, the filter could also allow any line with no `taid` although you could still end up seeing neighbor cities. But if they're that gray color it wouldn't stand out or cause much confusion, at least.

**Comment by davidheyman** [comment]
Yeah. Let's allow NULL taid's unless any change has been made to filters in which case hide them.

Can you do this on the new-data branch? If that's causing trouble, just do it on a separate one off master and I can merge it in.
