### ISSUE TITLE
Delete stale branches

### ISSUE THREAD

**Issue by davidheyman** [axismaps/ridership#78]
The branches here are getting out of control. Can you check if the 2 stale branches (`geojson` and `tract-tiles`) have anything we need on them? They look abandoned to me, but wanted to check with you first.

**Comment by awoodruff** [comment]
They look safe to kill to me. It's some work on performance that we started but quit because I guess we found good enough solutions without it, and it doesn't look like there was enough committed to be useful even if we did need to work more on performance fixes.

You've probably already looked, but it seems to think there is documentation work to merge in from those branches, although as far as I can tell they aren't real changes.
