### ISSUE TITLE
Can’t select 2018 data in timeline

### ISSUE THREAD

**Issue by davidheyman** [axismaps/ridership#84]

**Comment by awoodruff** [comment]
Fixed by b14038822515ea1a874bfe322514bac48a3dcb7b, I think, the bug coming from the national summary not having data for that year. Should 2018 also be the default end year? 

Are there new years of census data? The region level map has a hard-coded year range of 2010–2016 for some reason, but could probably be made to use whatever years are in the data table.

**Comment by davidheyman** [comment]
Yes. It should default to latest year available. 

The census data now goes up to 2018 for everything except the jobs stuff.

**Comment by awoodruff** [comment]
Thanks. It will now default to the latest year. Apparently it's a more involved change to get census view to reflect the actual data year range, so the year dropdown there just goes up to the same end year as the national data.

Also notable is that the national/region summary flag is generally going to look like it's missing by default, at least for now, because the summary data is only up to 2017.
