### ISSUE TITLE
Update data story to use latest year

### ISSUE THREAD

**Issue by davidheyman** [axismaps/ridership#85]

**Comment by awoodruff** [comment]
@davidheyman are we still keeping the data story in a submodule? I can make a change (and a couple other fixes) over in that repo but want to double check that it shouldn't just be moved into this one. I forget why it was separate.

Also, the data story loads embedded maps from insights.transitcenter.org and thus perhaps would not work with newer data if some recent fixes are not online; do you recall if there was a reason it can't use URLs instead?

**Comment by davidheyman** [comment]
The only reason it was in the submodule was because it was easier to manage the different dependencies. If it's easy to move into this without messing up the different build systems and such, there's no reason not to do it.

**Comment by awoodruff** [comment]
Think I'll leave it alone instead of trying to mess with build systems! I made the fix over there and also switched to relative URLs for the iframes here: https://github.com/axismaps/ridership-data-story/commit/c26c4a9c34f30dfc6c958a59edf8faf593e1e889. Not totally sure if that's actually okay to do, but it does let a recent bug fix come through locally for something that was driving me bananas for a long time!
