### ISSUE TITLE
Filtering for frequent transit isn't working correctly in Philadelphia

### ISSUE THREAD

**Issue by davidheyman** [axismaps/ridership#98]
Seems to only be showing frequent service for PATCO and not SEPTA and other agencies.

**Comment by awoodruff** [comment]
There's a note in here which I think concludes the same thing: https://github.com/axismaps/ridership/issues/66#issuecomment-626023800. But also there is an additional agency that matches (NJ Transit) but doesn't appear on the map. So if you uncheck all the agencies you still see some tracts because of that.
